### ISSUE TITLE
FModel can't read multiple paks correcly

### ISSUE THREAD

**Issue by Mirrorman95** [iAmAsval/FModel#238] opened 2022-01-05 05:33 UTC
### Game

Samurai Jack: Battle Through Time

### Error

```shell
I recently updated to UModel 4.2.1.0. And I know FModel absolutely does not support modding. But, I didn't have the problem I'm having with previous versions of FModel, so it felt reasonable to report the issue.
I have multiple paks in \Steam\steamapps\common\SamuraiJack\SJGAME\Content\Paks, the folder containing the Samurai Jack game data paks. The largest pak is the one the game originally came with. There are several smaller ones containing texture and audio mods I made or downloaded. In previous versions of FModel, opening one of those smaller paks would allow you to see the modded textures therein. But in this version of FModel, every time I open any pak at all, the image and audio preview windows only show me the original, pre-mod versions of those textures and sounds in the game's original pak, regardless of what is in the smaller pak itself. And I'm positive the paks have different images inside them. And when I try to load the paks in my old copy of FModel 3, which didn't have this problem, it doesn't do anything, it just insults me by saying "Don't be an idiot, update your fmodel". Again, I know FModel absolutely does not support modding, but there are games out there where multiple paks in one folder are just part of the game or DLC or something, and thus the bug still seems valid.
```

### Reproduction steps

1. Open FModel.
2. Set the settings and folders to any pak folder of an Unreal Engine 4 game that has multiple different paks in it that share files that would override each other depending on load order.
3. Preview the analogous files in the paks and check for any differences.

**Comment by iAmAsval** [comment] 2022-01-05 06:37
duplicate of https://github.com/iAmAsval/FModel/issues/204

**Closed by iAmAsval** 2022-01-05 06:37 UTC
Labels: bug
