### ISSUE TITLE
Aes

### ISSUE THREAD

**Issue by MrSquid1yt** [iAmAsval/FModel#55] opened 2020-05-14 17:02 UTC
hello the newest aes key not working i have the newest version of fmodel
0xDCC3C6D54873F20E247E942323AAAE74C310D3E6B01CCC5C87D3B0563F3EBC0C not working with your PAK-Data

**Comment by iAmAsval** [comment] 2020-05-14 17:07
make sure your game is up to date

**Comment by MrSquid1yt** [comment] 2020-05-14 17:13
it is

**Comment by iAmAsval** [comment] 2020-05-14 17:17
can you send the latest log file in `/your output folder here/Logs/` folder

**Comment by MrSquid1yt** [comment] 2020-05-14 17:41
[FModel-Log-2020-05-14.txt](https://github.com/iAmAsval/FModel/files/4630043/FModel-Log-2020-05-14.txt)

**Comment by FabianFG** [comment] 2020-05-14 17:51
it isnt up to date. Fortnite doesnt have pak1000+ since a few versions

**Comment by AyeTSG** [comment] 2020-05-14 20:46
Closed as the issue is invalid / for an older version of Fortnite.

**Closed by AyeTSG** 2020-05-14 20:46 UTC
